// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

const isConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
if (!isConfigured) {
  // Provide a clearer message in the browser console rather than failing silently with a blank page.
  // This module is lazy-loaded via routes, so it won't affect pages that don't use Supabase.
  // To fix: add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to your .env
  // or migrate affected pages to use the JWT backend client in src/lib/api.ts.
  // eslint-disable-next-line no-console
  console.warn(
    "Supabase is not configured. Set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env to enable Supabase features. Using a safe no-op client for now."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type SupabaseLike = ReturnType<typeof createClient<Database>>;

function makeNoopClient(): SupabaseLike {
  const noerr = null as unknown as null;
  const notConfigured = { message: 'Supabase not configured' } as any;
  const chain = () => ({
    insert: async () => ({ data: null, error: notConfigured }),
    update: async () => ({ data: null, error: notConfigured }),
    select: async () => ({ data: null, error: notConfigured }),
    delete: async () => ({ data: null, error: notConfigured }),
    eq: () => chain(),
  });
  return {
    // @ts-ignore - soft shim shape
    auth: {
      getUser: async () => ({ data: { user: null }, error: null }),
      signOut: async () => ({ error: noerr }),
      signUp: async () => ({ data: { user: null }, error: notConfigured }),
    },
    // @ts-ignore - soft shim shape
    from: () => chain(),
    // @ts-ignore - soft shim shape
    rpc: async () => ({ data: null, error: notConfigured }),
    // @ts-ignore - soft shim shape
    functions: {
      invoke: async () => ({ data: null, error: notConfigured }),
    },
    // @ts-ignore - soft shim shape
    removeChannel: () => {},
  } as unknown as SupabaseLike;
}

export const supabase: SupabaseLike = isConfigured
  ? createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : makeNoopClient();